# Generated by Django 2.0.2 on 2018-04-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(null=True)),
                ('casualties', models.IntegerField(null=True)),
                ('commander_code', models.CharField(max_length=20, null=True)),
                ('battle_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Battle')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Countries')),
            ],
        ),
    ]
