# Generated by Django 2.0.2 on 2018-04-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_battleparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePhotos',
            fields=[
                ('photo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('batle_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Battle')),
            ],
        ),
    ]
