# Generated by Django 2.0.2 on 2018-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180414_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesCoords',
            fields=[
                ('battle_year', models.IntegerField(primary_key=True, serialize=False)),
                ('coordinates', models.TextField(null=True)),
            ],
        ),
    ]
