# Generated by Django 2.0.2 on 2018-05-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_countriescoords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlephotos',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
