# Generated by Django 2.0.2 on 2018-06-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180531_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('name_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('shortened_name', models.TextField(null=True)),
                ('achievements', models.TextField(null=True)),
                ('fate', models.TextField(null=True)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Countries')),
            ],
        ),
    ]
