# Generated by Django 2.0.2 on 2018-06-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20180606_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePhotos',
            fields=[
                ('photo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True)),
                ('used_as', models.CharField(max_length=50, null=True)),
                ('person_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.People')),
            ],
        ),
    ]
