# Generated by Django 2.0.2 on 2018-06-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_peoplephotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_year', models.IntegerField(null=True)),
                ('location_left', models.FloatField(null=True)),
                ('location_top', models.FloatField(null=True)),
                ('battle_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Battle')),
            ],
        ),
    ]
