# Generated by Django 2.0.2 on 2018-06-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_battletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('glocation_left', models.FloatField(null=True)),
                ('glocation_top', models.FloatField(null=True)),
                ('battle_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.BattleTag')),
            ],
        ),
    ]
