# Generated by Django 2.0.2 on 2018-06-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_battlegroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattleGroups',
            new_name='GroupedBattles',
        ),
    ]
