# Generated by Django 2.0.2 on 2018-06-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20180610_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleGroups',
            fields=[
                ('group_code', models.IntegerField(primary_key=True, serialize=False)),
                ('glocation_left', models.FloatField(null=True)),
                ('glocation_top', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupedbattles',
            name='glocation_left',
        ),
        migrations.RemoveField(
            model_name='groupedbattles',
            name='glocation_top',
        ),
        migrations.AlterField(
            model_name='groupedbattles',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.BattleGroups'),
        ),
    ]
