# Generated by Django 2.0.2 on 2018-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20180610_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='battletag',
            name='in_a_group',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
