# Generated by Django 2.0.2 on 2018-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_battletag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedLinks',
            fields=[
                ('link', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('domain', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
