# Generated by Django 2.0.2 on 2018-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_suggestedlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIps',
            fields=[
                ('ip_addr', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('banned_on', models.DateField(null=True)),
            ],
        ),
    ]
