# Generated by Django 2.0.2 on 2018-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_bannedips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=500)),
                ('person_email', models.CharField(max_length=500)),
                ('person_subject', models.CharField(max_length=500)),
                ('person_description', models.TextField()),
                ('person_ip_addr', models.CharField(max_length=40)),
            ],
        ),
    ]
